GetCredentialTypes:
   Master_GetApplicationConfigs_smoke:
      endPoint: /v1/masterdata/applicationconfigs
      uniqueIdentifier: TC_Masterdata_GetApplicationConfigs_01
      description: Retrieve Application Configs by all valid data
      role: admin
      checkErrorsOnlyInResponse: true
      restMethod: get
      inputTemplate: masterdata/GetApplicationConfigs/getApplicationConfigs
      outputTemplate: masterdata/GetApplicationConfigs/getApplicationConfigsResult
      input: '{
      }'
      output: '{
      }'