apiVersion: v2
name: admin-service
description: A Helm chart for MOSIP Admin module
type: application
version: 1.3.0-beta.1
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - admin
  - kernel
maintainers:
  - email: info@mosip.io
    name: MOSIP
